
with categories as (
select str_to_date(date, '%m/%d/%Y' ) as date, description,
CASE WHEN DESCRIPTION LIKE '%QUADPAY%' THEN 'INCOME' 
	WHEN DESCRIPTION LIKE '%SAINT PETERS%' THEN 'INCOME'
    WHEN DESCRIPTION LIKE '%RAINBOW CLEANERS%' THEN 'CLEANERS'
    WHEN DESCRIPTION LIKE '%COFFEE%' THEN 'COFFEE'
    WHEN DESCRIPTION LIKE '%RITE AID%' THEN 'CONVENIENCE STORE'
    WHEN DESCRIPTION LIKE '%CHINA%' THEN 'RESTAURANT'
    WHEN DESCRIPTION LIKE '%GOLDMAN SACHS%' THEN 'TRANSFER_TO_EXTERNAL_ACCOUNT'
    WHEN DESCRIPTION LIKE '%PAYMENT%' THEN 'BILL PAYMENT'
    WHEN DESCRIPTION LIKE '%PAYROLL%' THEN 'INCOME'
    WHEN DESCRIPTION LIKE '%HONDA%' THEN 'BILL PAYMENT'
    WHEN DESCRIPTION LIKE '%YAD ELIEZER%' THEN 'CHARITY'
    WHEN DESCRIPTION LIKE '%LOIS E. SHULM%' THEN 'HEALTH'
    WHEN DESCRIPTION LIKE '%TARGET%' THEN 'TARGET'
    WHEN DESCRIPTION LIKE '%TOMCHEI%' THEN 'CHARITY'
    WHEN DESCRIPTION LIKE '%OIL%' THEN 'CAR'
    WHEN DESCRIPTION LIKE '%SUNOCO%' THEN 'CAR'
    WHEN DESCRIPTION LIKE '%DUNKIN%' THEN 'COFFEE'
    WHEN DESCRIPTION LIKE '%STARBUCKS%' THEN 'COFFEE'
    WHEN DESCRIPTION LIKE '%SHEETZ%' THEN 'CAR'
    WHEN DESCRIPTION LIKE '%STOP & SHOP%' THEN 'GROCERIES'
    WHEN DESCRIPTION LIKE '%INSTACART%' THEN 'GROCERIES'
    WHEN DESCRIPTION LIKE '%SUNOCO%' THEN 'GAS'
    WHEN DESCRIPTION LIKE '%PSEG%' THEN 'BILL PAYMENT'
    WHEN DESCRIPTION LIKE '%PIZZA%' THEN 'RESTAURANT'
    WHEN DESCRIPTION LIKE '%SUSHI%' THEN 'RESTAURANT'
    WHEN DESCRIPTION LIKE '%VERIZON%' THEN 'BILL PAYMENT'
    WHEN DESCRIPTION LIKE '%OPTIMUM%' THEN 'BILL PAYMENT'
    WHEN DESCRIPTION LIKE '%DEPT EDUCATION%' THEN 'CHARITY'
    WHEN DESCRIPTION LIKE '%ONLINE PMT%' THEN 'BILL PAYMENT'
    ELSE 'OTHER'
    END AS category,
    amount
 from mint.f_transactions_raw 
 )
 select year(date), month(date), category, sum(amount) as amount_sum 
 from categories where category <> 'TRANSFER_TO_EXTERNAL_ACCOUNT' group by 1,2,3 order by 1, 2 
 