
with categories as (
select str_to_date(date, '%m/%d/%Y' ) as date, description,
CASE WHEN DESCRIPTION LIKE '%QUADPAY%' THEN 'INCOME' 
                            WHEN DESCRIPTION LIKE '%SAINT PETERS%' THEN 'INCOME'
                            WHEN DESCRIPTION LIKE '%RAINBOW CLEANERS%' THEN 'CLEANERS'
                            WHEN DESCRIPTION LIKE '%COFFEE%' THEN 'COFFEE'
                            WHEN DESCRIPTION LIKE '%RITE AID%' THEN 'CONVENIENCE STORE'
                            WHEN DESCRIPTION LIKE '%CHINA%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%GOLDMAN SACHS%' THEN 'TRANSFER_TO_EXTERNAL_ACCOUNT'
                            WHEN DESCRIPTION LIKE '%PAYMENT%' THEN 'BILL PAYMENT'
                            WHEN DESCRIPTION LIKE '%PAYROLL%' THEN 'INCOME'
                            WHEN DESCRIPTION LIKE '%HONDA%' THEN 'BILL PAYMENT'
                            WHEN DESCRIPTION LIKE '%YAD ELIEZER%' THEN 'CHARITY'
                            WHEN DESCRIPTION LIKE '%LOIS E. SHULM%' THEN 'HEALTH'
                            WHEN DESCRIPTION LIKE '%TARGET%' THEN 'TARGET'
                            WHEN DESCRIPTION LIKE '%TOMCHEI%' THEN 'CHARITY'
                            WHEN DESCRIPTION LIKE '%OIL%' THEN 'CAR'
                            WHEN DESCRIPTION LIKE '%SUNOCO%' THEN 'CAR'
                            WHEN DESCRIPTION LIKE '%DUNKIN%' THEN 'COFFEE'
                            WHEN DESCRIPTION LIKE '%STARBUCKS%' THEN 'COFFEE'
                            WHEN DESCRIPTION LIKE '%SHEETZ%' THEN 'CAR'
                            WHEN DESCRIPTION LIKE '%STOP & SHOP%' THEN 'GROCERIES'
                            WHEN DESCRIPTION LIKE '%INSTACART%' THEN 'GROCERIES'
                            WHEN DESCRIPTION LIKE '%SUNOCO%' THEN 'GAS'
                            WHEN DESCRIPTION LIKE '%PSEG%' THEN 'BILL PAYMENT'
                            WHEN DESCRIPTION LIKE '%PIZZA%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%SUSHI%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%VERIZON%' THEN 'BILL PAYMENT'
                            WHEN DESCRIPTION LIKE '%OPTIMUM%' THEN 'BILL PAYMENT'
                            WHEN DESCRIPTION LIKE '%DEPT EDUCATION%' THEN 'CHARITY'
                            WHEN DESCRIPTION LIKE '%ONLINE PMT%' THEN 'BILL PAYMENT'
                            WHEN DESCRIPTION LIKE '%Amazon%' THEN 'AMAZON'
                            WHEN DESCRIPTION LIKE '%CHASE CREDIT%' THEN 'BILL PAYMENT'
                            WHEN DESCRIPTION LIKE '%Trnsfr%' THEN 'TRANSFER_TO_EXTERNAL_ACCOUNT'
                            WHEN DESCRIPTION LIKE '%FLORA%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%Bill Pay%' THEN 'BILL PAYMENT'
                            WHEN DESCRIPTION LIKE '%Check%' THEN 'MISC'
                            WHEN DESCRIPTION LIKE '%transfer%' THEN 'TRANSFER_TO_EXTERNAL_ACCOUNT'
                            WHEN DESCRIPTION LIKE '%BLUESTONE%' THEN 'COFFEE'
                            WHEN DESCRIPTION LIKE '%RWJ NEW%' THEN 'HEALTH'
                            WHEN DESCRIPTION LIKE '%SPOTIFY%' THEN 'BILL PAYMENT'
                            WHEN DESCRIPTION LIKE '%APPLE%' THEN 'BILL PAYMENT'
                            WHEN DESCRIPTION LIKE '%ATM%' THEN 'MISC'
                            WHEN DESCRIPTION LIKE '%Marcus Invest%' THEN 'TRANSFER_TO_EXTERNAL_ACCOUNT'
                            WHEN DESCRIPTION LIKE '%DISNEY%' THEN 'INCOME'
                            WHEN DESCRIPTION LIKE '%MTA%' THEN 'TRAVEL'
                            WHEN DESCRIPTION LIKE '%WELLS FARGO%' THEN 'BILL PAYMENT'
                            WHEN DESCRIPTION LIKE '%AMZN%' THEN 'AMAZON'
                            WHEN DESCRIPTION LIKE '%BAKERY%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%WHOLEFDS%' THEN 'GROCERIES'
                            WHEN DESCRIPTION LIKE '%TRANSACTION FEE%' THEN 'MISC'
                            WHEN DESCRIPTION LIKE '%MINI GOLF%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%NINTENDO%' THEN 'PERSONAL'
                            WHEN DESCRIPTION LIKE '%BRIDGE TURKISH%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%LYFT%' THEN 'TRAVEL'
                            WHEN DESCRIPTION LIKE '%UBER%' THEN 'TRAVEL'
                            WHEN DESCRIPTION LIKE '%BED BATH%' THEN 'HOUSE'
                            WHEN DESCRIPTION LIKE '%CAFE%' THEN 'COFFEE'
                            WHEN DESCRIPTION LIKE '%RACEWAY%' THEN 'CAR'
                            WHEN DESCRIPTION LIKE '%CVS%' THEN 'CONVENIENCE STORE'
                            WHEN DESCRIPTION LIKE '%DERECHETZCH%' THEN 'CHARITY'
                            WHEN DESCRIPTION LIKE '%STAUF%' THEN 'COFFEE'
                            WHEN DESCRIPTION LIKE '%UNITED%' THEN 'TRAVEL'
                            WHEN DESCRIPTION LIKE '%CAR%' THEN 'CAR'
                            WHEN DESCRIPTION LIKE '%FEDEX%' THEN 'MISC'
                            WHEN DESCRIPTION LIKE '%DERECH%' THEN 'CHARITY'
                            WHEN DESCRIPTION LIKE '%KOLLEL%' THEN 'CHARITY'
                            WHEN DESCRIPTION LIKE '%WITHDRWL%' THEN 'MISC'
                            WHEN DESCRIPTION LIKE '%NJT%' THEN 'TRAVEL'
                            WHEN DESCRIPTION LIKE '%DOLLAR-A-DAY%' THEN 'CHARITY'
                            WHEN DESCRIPTION LIKE '%CITRON%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%GREAT CLIPS%' THEN 'BILL PAYMENT'
                            WHEN DESCRIPTION LIKE '%PENSTOCK%' THEN 'COFFEE'
                            WHEN DESCRIPTION LIKE '%HOTEL%' THEN 'TRAVEL'
                            WHEN DESCRIPTION LIKE '%RESTAURANT%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%PAYPAL%' THEN 'MISC'
                            WHEN DESCRIPTION LIKE '%WALGREENS%' THEN 'CONVENIENCE STORE'
                            WHEN DESCRIPTION LIKE '%NAILS%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%GIVING%' THEN 'CHARITY'
                            WHEN DESCRIPTION LIKE '%AIRBNB%' THEN 'TRAVEL'
                            WHEN DESCRIPTION LIKE '%STOP &%' THEN 'GROCERIES'
                            WHEN DESCRIPTION LIKE '%BUDGET.COM%' THEN 'TRAVEL'
                            WHEN DESCRIPTION LIKE '%SPIRIT%' THEN 'TRAVEL'
                            WHEN DESCRIPTION LIKE '%CLEANERS%' THEN 'CLEANERS'
                            WHEN DESCRIPTION LIKE '%DUANE READE%' THEN 'CONVENIENCE STORE'
                            WHEN DESCRIPTION LIKE '%GET AIR%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%VENDING%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%CONG.%' THEN 'CHARITY'
                            WHEN DESCRIPTION LIKE '%7-ELEVEN%' THEN 'CAR'
                            WHEN DESCRIPTION LIKE '%GLATT 27%' THEN 'GROCERIES'
                            WHEN DESCRIPTION LIKE '%BEXLEY MKT%' THEN 'GROCERIES'
                            WHEN DESCRIPTION LIKE '%TRADER JOE%' THEN 'GROCERIES'
                            WHEN DESCRIPTION LIKE '%HEADWAY%' THEN 'HEALTH'
                            WHEN DESCRIPTION LIKE '%EXXON%' THEN 'CAR'
                            WHEN DESCRIPTION LIKE '%CHAI%' THEN 'CHARITY'
                            WHEN DESCRIPTION LIKE '%BUY BUY%' THEN 'GENERAL'
                            WHEN DESCRIPTION LIKE '%HYATT%' THEN 'TRAVEL'
                            WHEN DESCRIPTION LIKE '%KOSHER%' THEN 'GROCERIES'
                            WHEN DESCRIPTION LIKE '%HAVA JAVA%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%KOHL%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%SHOPRITE%' THEN 'GROCERIES'
                            WHEN DESCRIPTION LIKE '%OLD NAVY%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%AMC%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%SPEEDWAY%' THEN 'CAR'
                            WHEN DESCRIPTION LIKE '%COFF%' THEN 'COFFEE'
                            WHEN DESCRIPTION LIKE '%PHARMA%' THEN 'HEALTH'
                            WHEN DESCRIPTION LIKE '%CABOKI%' THEN 'HEALTH'
                            WHEN DESCRIPTION LIKE '%RITA%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%ROASTERY%' THEN 'COFFEE'
                            WHEN DESCRIPTION LIKE '%KROGER%' THEN 'GROCERIES'
                            WHEN DESCRIPTION LIKE '%FINES AND COSTS%' THEN 'MISC'
                            WHEN DESCRIPTION LIKE '%MUSIC%' THEN 'PERSONAL'
                            WHEN DESCRIPTION LIKE '%KITTIE%' THEN 'COFFEE'
                            WHEN DESCRIPTION LIKE '%CHASDEI%' THEN 'CHARITY'
                            WHEN DESCRIPTION LIKE '%BESTBUY%' THEN 'PERSONAL'
                            WHEN DESCRIPTION LIKE '%CHICKIES%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%SPA%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%PRIME%' THEN 'AMAZON'
                            WHEN DESCRIPTION LIKE '%ROCKNROLL%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%PINOT%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%WALMART%' THEN 'GENERAL'
                            WHEN DESCRIPTION LIKE '%BOUTIQUE%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%ZAGE%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%SKI%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%QUICK CHEK%' THEN 'COFFEE'
                            WHEN DESCRIPTION LIKE '%THEATRE%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%FIRESIDE%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%PARKING%' THEN 'MISC'
                            WHEN DESCRIPTION LIKE '%YOLANDA%' THEN 'MISC'
                            WHEN DESCRIPTION LIKE '%TJMA%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%KISSENA%' THEN 'GROCERIES'
                            WHEN DESCRIPTION LIKE '%PARTY%' THEN 'MISC'
                            WHEN DESCRIPTION LIKE '%STAPLES%' THEN 'GENERAL'
                            WHEN DESCRIPTION LIKE '%YERUSHALAYIM%' THEN 'CHARITY'
                            WHEN DESCRIPTION LIKE '%LAWRENCE%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%LOFT%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%ANTHRO%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%Travel%' THEN 'TRAVEL'
                            WHEN DESCRIPTION LIKE '%VICTORIA%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%TAXI%' THEN 'TRAVEL'
                            WHEN DESCRIPTION LIKE '%TAVLIN%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%GIVING%' THEN 'CHARITY'
                            WHEN DESCRIPTION LIKE '%SCHNITZ%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%PARK P%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%DELI KAS%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%MICHAELS%' THEN 'MISC'
                            WHEN DESCRIPTION LIKE '%CIRCLE K%' THEN 'CAR'
                            WHEN DESCRIPTION LIKE '%HUMBLE TOAST%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%ANN TAYLOR%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%BEDBATH%' THEN 'GENERAL'
                            WHEN DESCRIPTION LIKE '%SAMMY%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%ZAGAFEN%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%COLOR ME%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%BETH JACOB%' THEN 'CHARITY'
                            WHEN DESCRIPTION LIKE '%PARK DELI%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%RESTAU%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%NCSY%' THEN 'CHARITY'
                            WHEN DESCRIPTION LIKE '%DEPOSIT%' THEN 'INCOME'
                            WHEN DESCRIPTION LIKE '%ZENNI%' THEN 'HEALTH'
                            WHEN DESCRIPTION LIKE '%RWJ%' THEN 'HEALTH'
                            WHEN DESCRIPTION LIKE '%Duane%' THEN 'CONVENIENCE STORE'
                            WHEN DESCRIPTION LIKE '%TAXRFD%' THEN 'INCOME'
                            WHEN DESCRIPTION LIKE '%MUNICI%' THEN 'BILL PAYMENT'
                            WHEN DESCRIPTION LIKE '%MEOROT%' THEN 'CHARITY'
                            WHEN DESCRIPTION LIKE '%BBQ%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%BAKERIST%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%EXPEDIA%' THEN 'TRAVEL'
                            WHEN DESCRIPTION LIKE '%656 OCEAN%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%HILTON%' THEN 'TRAVEL'
                            WHEN DESCRIPTION LIKE '%REWARD%' THEN 'INCOME'
                            WHEN DESCRIPTION LIKE '%ROBINHOOD%' AND AMOUNT < 0  THEN 'TRANSFER_TO_EXTERNAL_ACCOUNT'
                            WHEN DESCRIPTION LIKE '%VENMO%' THEN 'MISC'
                            WHEN DESCRIPTION LIKE '%NATIONWIDE%' THEN 'HEALTH'
                            WHEN DESCRIPTION LIKE '%GRAETERS%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%WAL-MART%' THEN 'GENERAL'
                            WHEN DESCRIPTION LIKE '%EDEN%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%PARK DENTAL%' THEN 'HEALTH'
                            WHEN DESCRIPTION LIKE '%PARKCOLUMBUS%' THEN 'MISC'
                            WHEN DESCRIPTION LIKE '%CRIMSON%' THEN 'COFFEE'
                            WHEN DESCRIPTION LIKE '%BARNES%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%Theater of%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%CLOTHING%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%JUDAICA%' THEN 'GENERAL'
                            WHEN DESCRIPTION LIKE '%ROAD RUNNER%' THEN 'HEALTH'
                            WHEN DESCRIPTION LIKE '%KITCHEN%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%PIZZ%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%WEGMAN%' THEN 'GROCERIES'
                            WHEN DESCRIPTION LIKE '%AIRPORT%' THEN 'TRAVEL'
                            WHEN DESCRIPTION LIKE '%BLOOMINGDAL%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%FEE%' THEN 'MISC'
                            WHEN DESCRIPTION LIKE '%NJMVC%' THEN 'MISC'
                            WHEN DESCRIPTION LIKE '%FUNDRA%' THEN 'CHARITY'
                            WHEN DESCRIPTION LIKE '%CULVV%' THEN 'MISC'
                            WHEN DESCRIPTION LIKE '%WOMENS%' THEN 'WIFE'
                            WHEN DESCRIPTION LIKE '%GRILL%' THEN 'RESTAURANT'
                            WHEN DESCRIPTION LIKE '%MACY%' THEN 'WIFE'
                            ELSE 'UNCLASSIFIED'
                        END AS category,
                        amount 
 from mint.f_transactions_raw 
 )
 select year(date), month(date), category, sum(amount) as amount_sum 
 from categories where category <> 'TRANSFER_TO_EXTERNAL_ACCOUNT' group by 1,2,3 order by 1, 2 
 